import test from 'node:test';import assert from 'node:assert/strict';import {geminiMenu} from '../gemini.mjs';
test('Gemini receives actual image and parsed Korean JSON without client key',async()=>{const result=await geminiMenu(['data:image/png;base64,YQ=='],'test-key','gemini-3.8-flash',async(url,o)=>{const b=JSON.parse(o.body);assert.equal(o.headers['x-goog-api-key'],'test-key');assert.equal(b.contents[0].parts[1].inlineData.data,'YQ==');assert.equal(b.generationConfig.responseMimeType,'application/json');return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:'{"items":[{"original":"Risotto","korean":"리소토"}]}'}]}}]})};});assert.equal(result.items[0].korean,'리소토');});
test('Gemini quota refusal is explicit',async()=>{await assert.rejects(geminiMenu(['data:image/png;base64,YQ=='],'test','gemini-3.8-flash',async()=>({ok:false,status:429,json:async()=>({})})),/무료 사용 한도/);});

import {geminiOrder} from '../gemini.mjs';
test('order translation includes exact quantities, Korean request and Hangul pronunciation',async()=>{const result=await geminiOrder([{original:'Carbonara',korean:'카르보나라',quantity:2}],'it','치즈 빼고 주세요','test','gemini-3.1-flash-lite',async(url,o)=>{const b=JSON.parse(o.body);assert.match(b.contents[0].parts[0].text,/치즈 빼고 주세요/);assert.match(b.contents[0].parts[0].text,/"quantity":2/);return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({text:'Due carbonare senza formaggio, per favore.',pronunciation:'두에 카르보나레 센차 포르마조, 페르 파보레.',korean:'치즈 없이 카르보나라 2인분 주세요.'})}]}}]})};});assert.match(result.pronunciation,/두에/);assert.match(result.text,/senza formaggio/);});

import {geminiOfficialDescriptions} from '../gemini.mjs';
test('official descriptions translate source text with stable IDs and no price changes',async()=>{const r=await geminiOfficialDescriptions([{id:'0',original:'Battuta',officialDescription:'Carne con olio EVO.'}],'test','gemini-3.1-flash-lite',async(url,o)=>{const b=JSON.parse(o.body);assert.match(b.contents[0].parts[0].text,/Carne con olio EVO/);assert.match(b.contents[0].parts[0].text,/원문에 없는 재료/);return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({items:[{id:'0',korean:'소고기 육회',description:'올리브유를 곁들인 고기.',ingredients:['고기','올리브유'],cooking:''}]})}]}}]})};});assert.equal(r[0].id,'0');assert.equal(r[0].description,'올리브유를 곁들인 고기.');});
