import {readFileSync} from 'node:fs';
import test from 'node:test';import assert from 'node:assert/strict';
import {getRestaurantCatalog,enrichFromCatalog,isCatalogURL} from '../restaurant-catalog.mjs';
test('complete official catalog retains all translated entries and exact product image sources',()=>{const c=getRestaurantCatalog();assert.equal(c.items.length,c.totalCount);assert.equal(new Set(c.items.map(i=>i.id)).size,c.totalCount);for(const i of c.items){assert.ok(i.korean.trim());assert.ok(i.description.trim());assert.ok(i.sources[0].url.endsWith('/'+i.id));if(i.image&&!i.image.representative)assert.equal(i.image.source,i.sources[0].url);}});
test('cached dish match preserves photographed price and connects its own official photo',()=>{const c=getRestaurantCatalog();const p=c.items.find(i=>i.original==='BATTUTA DI CHIANINA');assert.ok(p);const result=enrichFromCatalog([{id:'photo-0',original:'Battuta di Chianina',price:13.5}]);assert.equal(result.matched,1);const i=result.items[0];assert.equal(i.id,'photo-0');assert.equal(i.price,13.5);assert.equal(i.catalogProductId,p.id);assert.equal(i.description,p.description);assert.deepEqual(i.image,p.image);assert.equal(i.officialPrice,p.officialPrice);});
test('unknown and ambiguous names keep their photo interpretation rather than attach arbitrary official dishes',()=>{const i={id:'0',original:'Baccalà',price:null,description:'OCR interpretation'};const result=enrichFromCatalog([i]);assert.equal(result.matched,0);assert.deepEqual(result.items[0],i);assert.ok(!isCatalogURL('https://11729.ordinaincloud.it.evil.test/menu/13361/products'));assert.ok(!isCatalogURL('https://11729.ordinaincloud.it/menu/999/products'));});
test('every saved exact official name maps back to the same product ID',()=>{const c=getRestaurantCatalog();for(const p of c.items){const r=enrichFromCatalog([{id:'ocr',original:p.original,price:null}]);assert.equal(r.items[0].catalogProductId,p.id,p.original);}});

test('all 62 food dishes have verified local photographs and readable Korean names',()=>{const foods=getRestaurantCatalog().items.filter(i=>['antipasti','zuppe','pasta','SECONDI','contorni','FORMAGGIO','DESSERT'].includes(i.category));assert.equal(foods.length,62);for(const i of foods){assert.ok(i.image?.url.startsWith('/assets/solita/'),i.original);const bytes=readFileSync(new URL('../public'+i.image.url,import.meta.url));assert.equal(bytes[0],255);assert.equal(bytes[1],216);assert.ok(i.description.length<250,i.original);assert.ok(!/[A-Z]{3}/.test(i.korean),i.original);}});
test('photographed pork with apples uses a representative photo without claiming a restaurant product match',()=>{const i=enrichFromCatalog([{id:'pork',original:'Maiale alle Mele Gold Rush',price:14.5}]).items[0];assert.equal(i.korean,'사과를 곁들인 돼지고기');assert.equal(i.price,14.5);assert.ok(i.image.representative);assert.ok(!i.catalogProductId);});
