const page=await figma.getNodeByIdAsync('341:2');
for(const style of ['Regular','Medium','Bold'])await figma.loadFontAsync({family:'Noto Sans KR',style});
const created=[];const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const vars={};for(const [key,id] of Object.entries({accent:'VariableID:341:6',surface:'VariableID:341:8',ink:'VariableID:341:10',muted:'VariableID:341:12'}))vars[key]=await figma.variables.getVariableByIdAsync(id);
const coll=(await figma.variables.getLocalVariableCollectionsAsync()).find(c=>c.id==='VariableCollectionId:341:4');
const radius=figma.variables.createVariable('radius/button',coll,'FLOAT');radius.scopes=['CORNER_RADIUS'];radius.setValueForMode(coll.modes[0].modeId,14);radius.setVariableCodeSyntax('WEB','var(--radius)');
const space=figma.variables.createVariable('spacing/content',coll,'FLOAT');space.scopes=['GAP'];space.setValueForMode(coll.modes[0].modeId,16);space.setVariableCodeSyntax('WEB','var(--space)');
const styleIDs={body:'S:471be18d8d8eaefd4b7dbf4b7046853b3a561bdc,',title:'S:d908e5529447a34c80a960d9fef8fcf815e5b294,',button:'S:6afe26597f53f1363f03da47f97507dc1c7f1268,',caption:'S:0405ad4a6beb9cb72394810199e858db69735dfb,'};
const paint=k=>figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb({accent:'#ff4b00',surface:'#ffffff',ink:'#252629',muted:'#86888b'}[k])},'color',vars[k]);
const {componentSet,variants}=await createComponentWithVariants({name:'한입 유럽 / Button',description:'웹 프로토타입과 같은 오렌지 버튼. Label 텍스트와 Style을 바꿀 수 있습니다.',variantAxes:{Style:['Primary','Outline']},baseProps:{width:328,height:50,radius:14,layoutMode:'HORIZONTAL',padding:{left:16,right:16}},page});
componentSet.x=2300;componentSet.y=100;created.push(componentSet.id);
function txt(parent,value,key='body',color='ink',width=328){const t=figma.createText();parent.appendChild(t);t.fontName={family:'Noto Sans KR',style:key==='button'?'Bold':key==='title'?'Medium':'Regular'};t.characters=value;t.textStyleId=styleIDs[key];t.textAutoResize='HEIGHT';t.resize(width,20);t.fills=[paint(color)];created.push(t.id);return t;}
const labelProperty=componentSet.addComponentProperty('Label','TEXT','버튼');
for(let i=0;i<variants.length;i++){const v=variants[i];v.fills=[paint(i===0?'accent':'surface')];if(i===1){v.strokes=[paint('accent')];v.strokeWeight=1;}v.setBoundVariable('cornerRadius',radius);v.setBoundVariable('paddingLeft',space);v.setBoundVariable('paddingRight',space);const t=txt(v,'버튼','button',i===0?'surface':'accent',250);t.textAlignHorizontal='CENTER';t.componentPropertyReferences={characters:labelProperty};created.push(v.id);}
const wrapper=figma.createAutoLayout('HORIZONTAL');page.appendChild(wrapper);wrapper.name='추가 화면 · 식당 확인과 5개 하단 탭';wrapper.itemSpacing=60;wrapper.resize(2040,780);wrapper.primaryAxisSizingMode='AUTO';wrapper.counterAxisSizingMode='FIXED';wrapper.x=160;wrapper.y=1900;wrapper.fills=[];created.push(wrapper.id);
function panel(parent,name,vertical=true){const n=figma.createAutoLayout(vertical?'VERTICAL':'HORIZONTAL');parent.appendChild(n);n.name=name;n.fills=[];n.itemSpacing=10;n.resize(328,20);n.primaryAxisSizingMode='AUTO';n.counterAxisSizingMode='FIXED';created.push(n.id);return n;}
function button(parent,label,outline=false){const inst=variants[outline?1:0].createInstance();parent.appendChild(inst);const p=Object.keys(inst.componentProperties).find(k=>k.startsWith('Label'));inst.setProperties({[p]:label});created.push(inst.id);return inst;}
function card(parent,title,desc){const c=panel(parent,title);c.paddingTop=16;c.paddingBottom=16;c.paddingLeft=16;c.paddingRight=16;c.fills=[paint('surface')];c.strokes=[{type:'SOLID',color:rgb('#e5e5e7')}];c.cornerRadius=16;c.resize(328,60);txt(c,title,'title','ink',296);if(desc)txt(c,desc,'caption','muted',296);return c;}
function input(parent,label,value){txt(parent,label,'caption');const box=card(parent,value||'입력해주세요.','');box.children[0].fontSize=13;return box;}
const screens=[];
for(const [index,name,title] of [[9,'09 식당 확인','식당 확인'],[10,'10 찜한 음식','찜한 음식'],[11,'11 주문 내역','주문 내역'],[12,'12 동반인','동반인'],[13,'13 마이페이지','MY']]){
 const screen=figma.createAutoLayout('VERTICAL');wrapper.appendChild(screen);screen.name=name;screen.resize(360,780);screen.primaryAxisSizingMode='FIXED';screen.counterAxisSizingMode='FIXED';screen.fills=[paint('surface')];screen.clipsContent=true;created.push(screen.id);screens.push(screen);
 const header=panel(screen,'Header',false);header.resize(360,64);header.primaryAxisSizingMode='FIXED';header.counterAxisSizingMode='FIXED';header.counterAxisAlignItems='CENTER';header.paddingLeft=16;header.paddingRight=16;header.itemSpacing=24;txt(header,index===13?'':'‹','title','ink',24);const heading=txt(header,title,'title','ink',232);heading.textAlignHorizontal=index===13?'LEFT':'CENTER';header.strokes=[{type:'SOLID',color:rgb('#eeeeef')}];header.strokeBottomWeight=1;
 const mode=panel(screen,'데모 안내');mode.paddingLeft=16;mode.paddingTop=5;mode.paddingBottom=5;mode.resize(360,25);mode.fills=[{type:'SOLID',color:rgb('#fff8f4')}];txt(mode,'예시 화면 · 실제 식당 정보와 다를 수 있어요','caption','accent');
 const content=panel(screen,'Content');content.resize(360,650);content.paddingLeft=16;content.paddingRight=16;content.paddingTop=20;content.itemSpacing=16;
 if(index===9){txt(content,'이 식당이 맞나요?','title');txt(content,'식당명을 찾지 못했어요. 위치로 찾거나 직접 검색해주세요.','caption','muted');input(content,'식당명 또는 주소','Trattoria, Roma');button(content,'검색');button(content,'내 위치로 가까운 식당 찾기',true);const c=card(content,'TRATTORIA · 예시 식당','Google Maps · 위치 후보 예시\n실제 GPS 검색 결과가 아닙니다.');button(content,'이 식당이 맞아요');button(content,'식당 확인 건너뛰기',true);}
 if(index===10){txt(content,'다시 만나고 싶은 맛','title');const row=card(content,'피렌체식 염장 대구 요리','Baccalà alla Fiorentina\nEUR 16.00 · 예시 메뉴');const photo=figma.createRectangle();row.appendChild(photo);photo.name='개별 음식 참고 사진';photo.resize(296,180);photo.cornerRadius=12;photo.fills=[{type:'IMAGE',imageHash:'a3ca2d06fea6b3a90871a9f4bb1e5e40ed0cc73a',scaleMode:'FILL'}];created.push(photo.id);txt(row,'원본 UI의 참고 이미지 · 실제 음식과 다를 수 있음','caption','muted',296);button(content,'음식 상세 보기',true);}
 if(index===11){txt(content,'여행의 맛 기록','title');txt(content,'저장한 주문 문장입니다. 식당에 자동 전송되지 않습니다.','caption','muted');card(content,'피렌체식 염장 대구 요리 1인분','예시 주문 · 2026. 10. 10.\nVorremmo ordinare una porzione di Baccalà alla Fiorentina, per favore.');button(content,'주문 문장 다시 보기',true);}
 if(index===12){txt(content,'함께라서 더 맛있게','title');txt(content,'취향과 알레르기 메모는 이 기기에 저장됩니다.','caption','muted');card(content,'예시 동반인','음식 취향: 담백한 음식\n알레르기: 메모 없음');input(content,'이름','함께 여행하는 사람');input(content,'음식 취향','담백한 음식, 매운 음식');input(content,'알레르기 메모','갑각류, 견과류 등');button(content,'동반인 추가');}
 if(index===13){const profile=panel(content,'프로필',false);profile.resize(328,62);const avatar=figma.createEllipse();profile.appendChild(avatar);avatar.resize(54,54);avatar.fills=[{type:'SOLID',color:rgb('#eff0f2')}];created.push(avatar.id);const copy=panel(profile,'프로필 이름');copy.resize(240,60);txt(copy,'함께 떠나는 미식가','title','ink',240);txt(copy,'유럽에서 만나는 우리 취향의 한 끼','caption','muted',240);card(content,'찜한 음식 1    주문 기록 1    동반인 1','이 기기에 저장된 여행 정보');card(content,'함께 여행하는 사람','음식 취향과 알레르기 메모');card(content,'여행 전 알아두면 좋은 것','현지 식사 문화와 주문 표현');card(content,'서비스 연결 상태','사진 AI · Places · 웹 이미지 검색');card(content,'개인정보와 저장','사진 전송 동의 · 위치 사용 안내');}
 if(index>9){const footer=figma.createAutoLayout('HORIZONTAL');screen.appendChild(footer);footer.layoutPositioning='ABSOLUTE';footer.name='5개 하단 탭';footer.resize(360,72);footer.x=0;footer.y=708;footer.primaryAxisSizingMode='FIXED';footer.counterAxisSizingMode='FIXED';footer.fills=[paint('surface')];footer.paddingTop=12;footer.strokes=[{type:'SOLID',color:rgb('#eeeeef')}];created.push(footer.id);for(const [j,label] of ['⌂\n홈','♡\n찜한 음식','▤\n주문 내역','♧\n동반인','◉\n마이페이지'].entries()){const t=txt(footer,label,'caption',j===index-9?'accent':'muted',72);t.textAlignHorizontal='CENTER';}}
}
const counts={};for(const n of wrapper.findAll(()=>true))counts[n.type]=(counts[n.type]||0)+1;
return {createdNodeIds:created,wrapperId:wrapper.id,frames:screens.map(f=>({id:f.id,name:f.name,w:f.width,h:f.height})),buttonSet:componentSet.id,variants:variants.map(v=>({id:v.id,name:v.name})),variableIds:[radius.id,space.id],types:counts,fontAssertion:wrapper.findAllWithCriteria({types:['TEXT']}).every(t=>t.fontName.family==='Noto Sans KR')};
