import {ordinaMenuAddress,readOrdinaMenu} from './ordina-menu.mjs';
import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';
const norm=s=>String(s||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const plain=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
export function publicAddress(ip){if(isIP(ip)===6)return /^2[0-9a-f]{3}:/i.test(ip)&&!/^2001:(?:db8|0):/i.test(ip);const a=ip.split('.').map(Number);return isIP(ip)===4&&![0,10,127].includes(a[0])&&a[0]<224&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&(a[1]===168||a[1]===0))&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&[18,19,51].includes(a[1]))&&!(a[0]===203&&a[1]===0);}
async function safeFetch(url,host){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||u.hostname!==host)throw Error('지원하지 않는 공식 사이트 주소입니다.');const addresses=await lookup(u.hostname,{all:true});if(!addresses.length||addresses.some(x=>!publicAddress(x.address)))throw Error('공식 웹사이트 주소를 확인할 수 없습니다.');const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(12000)});if(!r.ok||!r.headers.get('content-type')?.includes('text/html'))throw Error('웹 메뉴를 읽을 수 없습니다. PDF·로그인·동적 페이지는 직접 확인해주세요.');let text='';for await(const chunk of r.body){text+=Buffer.from(chunk).toString();if(text.length>1_500_000)throw Error('웹 메뉴가 너무 큽니다.');}return text;}
export function extractMenu(html,page){const result=[];const add=(x)=>{if(typeof x.name!=='string')return;let image=typeof x.image==='string'?x.image:Array.isArray(x.image)?x.image[0]:x.image?.url;try{image=image?new URL(image,page).href:null;if(image&&!image.startsWith('https://'))image=null;}catch{image=null;}result.push({name:plain(x.name),description:plain(x.description).slice(0,300),image,source:page});};
 for(const m of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const walk=x=>{if(!x||typeof x!=='object')return;if(['MenuItem','Product'].includes(x['@type']))add(x);for(const v of Object.values(x))if(typeof v==='object')Array.isArray(v)?v.forEach(walk):walk(v);};walk(JSON.parse(m[1]));}catch{}}
 // Only match a bounded item card with its own heading; never take a page hero image.
 for(const m of html.matchAll(/<(article|li)\b[^>]*>([\s\S]*?)<\/\1>/gi)){const card=m[2];if(card.length>5000)continue;const name=card.match(/<h[2-6]\b[^>]*>([\s\S]*?)<\/h[2-6]>/i)?.[1];if(!name)continue;add({name,description:card.match(/<p\b[^>]*>([\s\S]*?)<\/p>/i)?.[1]||'',image:card.match(/<img\b[^>]*src=["']([^"']+)/i)?.[1]});}return result;
}
export function matchOfficial(items,candidates){return items.map(i=>{const matches=candidates.filter(c=>(norm(c.name)===norm(i.original)||(c.aliases||[]).some(a=>norm(a)===norm(i.original))||c.matchedOriginal===i.original)&&norm(i.original).length>=4);if(!matches.length)return {...i};const c=matches.find(x=>x.description||x.image)||matches[0];return {...i,officialDescription:c.description||null,officialName:c.name,officialPrice:c.officialPrice??null,description:c.description?'공식 메뉴 원문: '+c.description:i.description,sourceLabel:'식당 공식 웹 메뉴 · 음식명 일치 · 원문 설명',sources:[{title:'공식 웹 메뉴',url:c.source}],image:c.image?{url:c.image,label:'공식 메뉴의 음식명과 일치하는 사진 · 자동 추출',source:c.source,authors:[],license:'공식 사이트 제공 이미지 · 원문 이용조건 확인'}:i.image};});}
export async function enrichOfficial(items,website){if(ordinaMenuAddress(website)){const r=await readOrdinaMenu(items,website);const enriched=matchOfficial(items,r.candidates);return {items:enriched,matched:enriched.filter(i=>i.officialName).length,pages:[website],provider:'ordina-in-cloud',failedItems:r.failures};}const home=new URL(website);if(home.protocol==='http:')home.protocol='https:';const html=await safeFetch(home.href,home.hostname);const pages=[{url:home.href,html}];const links=[];for(const m of html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){if(!/menu|menù|speisekarte|carte|carta|cardapio/i.test(m[1]+' '+plain(m[2])))continue;try{const u=new URL(m[1],home);if(ordinaMenuAddress(u.href))return enrichOfficial(items,u.href);if(u.hostname===home.hostname&&u.protocol==='https:'&&!/\.pdf(?:\?|$)/i.test(u.href)&&u.href!==home.href&&!links.includes(u.href))links.push(u.href);}catch{}}
 for(const url of links.slice(0,3)){try{pages.push({url,html:await safeFetch(url,home.hostname)});}catch{}}
 const candidates=pages.flatMap(p=>extractMenu(p.html,p.url));const enriched=matchOfficial(items,candidates);return {items:enriched,matched:enriched.filter(i=>i.sources?.some(s=>pages.some(p=>p.url===s.url))).length,pages:pages.map(p=>p.url)};
}
