const norm=s=>String(s||'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const plain=s=>String(s||'').replace(/<!--[\s\S]*?-->/g,'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
export function ordinaMenuAddress(url){try{const u=new URL(url),tenant=u.hostname.match(/^(\d+)\.ordinaincloud\.it$/)?.[1],config=u.pathname.match(/^\/menu\/(\d+)\/products(?:\/|$)/)?.[1];return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&tenant&&config?{tenant,config,url:u.origin+'/menu/'+config+'/products'}:null;}catch{return null;}}
export function resolveRestaurantMenu(place){if(norm(place?.name)==='osterialasolitazuppa'&&/chiusi/i.test(place.address||''))return 'https://11729.ordinaincloud.it/menu/13361/products';return place?.website||null;}
export function chooseOrdinaProduct(name,records){const key=norm(name);const exact=records.filter(p=>[p.descriptionLabel,p.description,...(p.sku||[]).flatMap(s=>[s.descriptionLabel,s.descriptionReceipt])].some(n=>norm(n)===key));if(exact.length===1)return exact[0];if(exact.length>1)return null;if(key.length<12)return null;const prefix=records.filter(p=>norm(p.descriptionLabel||p.description).startsWith(key));return prefix.length===1?prefix[0]:null;}
export function ordinaCandidate(product,source,config){const image=product.itemImages?.slice().sort((a,b)=>(a.position||0)-(b.position||0)).find(i=>{try{return new URL(i.imageUrl).protocol==='https:';}catch{return false;}})?.imageUrl;return {name:plain(product.descriptionLabel||product.description),aliases:(product.sku||[]).flatMap(s=>[s.descriptionLabel,s.descriptionReceipt]).filter(Boolean),description:plain(product.descriptionExtended).slice(0,700),image:image||null,source:source+'/'+encodeURIComponent(product.idCategory)+'/'+encodeURIComponent(product.id),officialPrice:product.prices?.find(p=>p.live&&p.idSalesPoint===Number(config))?.price??null};}
export async function readOrdinaMenu(items,url,fetcher=fetch){const address=ordinaMenuAddress(url);if(!address)throw Error('지원하지 않는 웹 메뉴 주소입니다.');const json=async(u,headers={})=>{const r=await fetcher(u,{headers,redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('공식 웹 메뉴 연결 실패 ('+r.status+')');const text=await r.text();if(text.length>2000000)throw Error('공식 웹 메뉴 응답이 너무 큽니다.');return JSON.parse(text);};
 const settings=await json('https://fidelity.ordinaincloud.it/tenants/'+address.tenant+'/settings.json');if(typeof settings.apiKey!=='string')throw Error('공개 웹 메뉴 설정을 읽지 못했습니다.');const headers={'api-key':settings.apiKey,'api-version':'4.23.0','Accept-Language':'it'},base='https://fidelity-services.cassanova.com/configs/'+address.config;const candidates=[],failures=[];let next=0;const seen=new Set();
 async function worker(){while(next<items.length){const i=items[next++];try{const query=new URLSearchParams({query:i.original,start:'0',limit:'30',deliveryMode:'WEB_MENU'});const list=await json(base+'/items/search?'+query,headers);const p=chooseOrdinaProduct(i.original,list.records||[]);if(!p||seen.has(p.id))continue;seen.add(p.id);const detail=await json(base+'/items/'+encodeURIComponent(p.id)+'?deliveryMode=WEB_MENU',headers);const product=detail.records?.find(x=>x.id===p.id);if(product)candidates.push({...ordinaCandidate(product,address.url,address.config),matchedOriginal:i.original});}catch{failures.push(i.original);}}}
 await Promise.all([worker(),worker(),worker()]);return {candidates,failures};
}
