import {readFileSync} from 'node:fs';
import {chooseOrdinaProduct} from './ordina-menu.mjs';
const catalog=JSON.parse(readFileSync(new URL('./data/restaurants/solita-zuppa.json',import.meta.url),'utf8'));
const reviews=JSON.parse(readFileSync(new URL('./data/restaurants/solita-zuppa-review.json',import.meta.url),'utf8'));
for(const p of catalog.items){const review=reviews[p.original];if(!review)continue;if(review.korean)p.korean=review.korean;if(review.officialSourceNote)p.officialSourceNote=review.officialSourceNote;for(const [from,to] of review.descriptionReplacements||[]){p.description=p.description.replaceAll(from,to);p.ingredients=p.ingredients.map(i=>i.replaceAll(from,to));}}
export const catalogURL='https://11729.ordinaincloud.it/menu/13361/products';
export function isCatalogURL(url){try{const u=new URL(url);return u.origin==='https://11729.ordinaincloud.it'&&/^\/menu\/13361\/products(?:\/|$)/.test(u.pathname);}catch{return false;}}
const photoOverrides=JSON.parse(readFileSync(new URL('./data/restaurants/solita-zuppa-photos.json',import.meta.url),'utf8'));
const byId=new Map(catalog.items.map(p=>[p.id,p]));
const records=catalog.items.map(p=>({...p,descriptionLabel:p.original,description:p.original,sku:p.aliases.map(descriptionLabel=>({descriptionLabel}))}));
const categoryNames={antipasti:'전채 요리',zuppe:'수프',pasta:'파스타',SECONDI:'메인 요리',contorni:'곁들임 요리',FORMAGGIO:'치즈',DESSERT:'디저트',SERVIZI:'서비스',ALLERGENI:'알레르기 안내',"12 MENU'":'세트 메뉴',"13 CAFFE'":'커피','000. COCKTAILS':'칵테일','15 BOLLICINE':'스파클링 와인','16 VINO ROSATO':'로제 와인','17 VINI BIANCHI':'화이트 와인','18 NOBILE DI MONTEPULCIANO':'노빌레 디 몬테풀차노','19  ROSSO DI MONTEPULCIANO':'로쏘 디 몬테풀차노','20 CHIANTI':'키안티','21 BRUNELLO':'브루넬로','22 ROSSO DI MONTALCINO':'로쏘 디 몬탈치노','23 PINOT NERO':'피노 네로','24 BOLGHERI':'볼게리','24 SYRAH':'시라','25 TOSCANA':'토스카나','26 PIEMONTE':'피에몬테','27 VENETO':'베네토','28 UMBRIA':'움브리아','29 LAZIO E CAMPANIA':'라치오 · 캄파니아','30 TRENTINO':'트렌티노','31 SICILIA E SARDEGNA':'시칠리아 · 사르데냐','32 LOMBARDIA':'롬바르디아','33 FRIULI':'프리울리','34 ABRUZZO':'아브루초','35 BASILICATA':'바실리카타','36 PUGLIA':'풀리아','37 FRANCIA':'프랑스 와인','38  VINI ESTERI':'해외 와인','39 VINI DOLCI':'디저트 와인',MAGNUM:'매그넘 와인'};
const categoryOrder=['antipasti','zuppe','pasta','SECONDI','contorni','FORMAGGIO','DESSERT',"12 MENU'","13 CAFFE'",'000. COCKTAILS',...Object.keys(categoryNames).filter(c=>!['antipasti','zuppe','pasta','SECONDI','contorni','FORMAGGIO','DESSERT',"12 MENU'","13 CAFFE'",'000. COCKTAILS'].includes(c))];
const nameKey=s=>String(s||'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const nameIndex=new Map();for(const p of records)for(const name of [p.original,...p.aliases]){const key=nameKey(name);if(!key)continue;if(!nameIndex.has(key))nameIndex.set(key,new Map());nameIndex.get(key).set(p.id,p);}
function matchCatalog(name){const matches=nameIndex.get(nameKey(name));if(matches)return matches.size===1?[...matches.values()][0]:null;return chooseOrdinaProduct(name,records);}
export function catalogItem(p){return {id:p.id,original:p.original,korean:p.korean,price:p.officialPrice,currency:'EUR',officialPrice:p.officialPrice,description:p.description==='공식 메뉴에 상세 설명이 없습니다.'?'구체적인 구성은 직원에게 확인해주세요.':p.description,ingredients:p.ingredients,cooking:p.cooking,taste:p.taste,allergens:[],estimated:false,officialName:p.original,officialDescription:p.officialDescription||null,officialTranslated:true,officialSourceNote:p.officialSourceNote||null,category:p.category,categoryKorean:categoryNames[p.category]||p.category,sourceLabel:'식당 공식 메뉴 · 미리 번역한 한국어 설명',sources:[{title:'식당 공식 메뉴',url:p.source}],image:photoOverrides[p.original]||(p.original==='PALLINA DI GELATO'?{url:catalog.items.find(i=>i.original==='GELATO').localImage||catalog.items.find(i=>i.original==='GELATO').images[0],label:'젤라또 대표 사진',representative:true,source:catalog.items.find(i=>i.original==='GELATO').source,authors:[]}:p.images.length?{url:p.localImage||p.images[0],label:p.korean+' 사진',source:p.source,authors:[]}:null)};}
export function getRestaurantCatalog(){return {...catalog,items:catalog.items.map(catalogItem).sort((a,b)=>(categoryOrder.indexOf(a.category)<0?999:categoryOrder.indexOf(a.category))-(categoryOrder.indexOf(b.category)<0?999:categoryOrder.indexOf(b.category))||a.original.localeCompare(b.original,'it'))};}
export function enrichFromCatalog(items){const enriched=items.map(i=>{const match=matchCatalog(i.original),p=match&&byId.get(match.id);if(!p){if(nameKey(i.original)==='maialeallemelegoldrush')return {...i,korean:'사과를 곁들인 돼지고기',description:'골드 러시 품종 사과를 곁들인 돼지고기 메뉴예요. 정확한 부위와 조리법은 직원에게 확인해주세요.',ingredients:['돼지고기','사과'],cooking:'직원에게 확인해주세요.',taste:'사과와 돼지고기를 함께 즐기는 메뉴예요.',image:photoOverrides['MAIALE ALLE MELE GOLD RUSH']};return {...i};}const c=catalogItem(p);return {...i,...c,id:i.id,original:i.original,price:i.price,catalogProductId:p.id,officialSnapshotDate:catalog.fetchedAt};});return {items:enriched,matched:enriched.filter(i=>i.catalogProductId).length,translated:enriched.filter(i=>i.catalogProductId&&i.officialDescription).length,catalogAvailable:true,catalogTotal:catalog.totalCount,website:catalogURL,snapshotDate:catalog.fetchedAt,warnings:['공식 메뉴 '+catalog.fetchedAt.slice(0,10)+' 기준으로 음식명·설명·사진을 연결했습니다. 촬영 가격은 유지하며 메뉴 변경 여부는 식당에서 확인해주세요.']};}
